#docker-compose.yml

version: '3.8'

services:
  frontend-nginx:
    # Dockerfile이 deploy/에 있지만, docker-compose.yml이 프로젝트 루트에 있으므로
    # 빌드 컨텍스트는 프로젝트의 루트 디렉토리(.)가 됩니다.
    build:
      context: .
      # Dockerfile의 경로는 이제 프로젝트 루트에서 deploy/Dockerfile 입니다.
      dockerfile: ./deploy/Dockerfile
    container_name: tmdb-frontend-nginx # 컨테이너 이름 지정
    ports:
      - "80:80" # 로컬 80 포트를 컨테이너 80 포트에 매핑
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    networks:
      - tmdb-app-network

networks:
  tmdb-app-network:
    driver: bridge