# deploy/docker-compose.yml

version: '3.8'

services:
  frontend-nginx:
    build:
      context: ../ # Dockerfile이 deploy/에 있지만, 빌드 컨텍스트는 프로젝트 루트
      dockerfile: ./deploy/Dockerfile # deploy/Dockerfile 지정
    ports:
      - "80:80" # 로컬 80 포트를 컨테이너 80 포트에 매핑
    volumes:
      # 로컬에서 변경사항 즉시 반영을 위해 개발 중에는 주석 해제 (단, 빌드된 dist 폴더가 필요)
      # - ../frontend/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Nginx 설정 파일 변경 시 즉시 반영
    restart: always # 컨테이너 항상 재시작